name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install wasm32-unknown-unknown
        run: |
          rustup target add wasm32-unknown-unknown

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: latest

      - name: Run tests
        run: |
          cargo test
          cargo test --target wasm32-unknown-unknown
        env:
          RUST_BACKTRACE: 1

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Update Cargo.toml version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}

          echo "Updating Cargo.toml version to: $VERSION"
          sed -i "s/^version = \".*\"/version = \"$VERSION\"/" Cargo.toml

          echo "Updated Cargo.toml:"
          grep '^version = ' Cargo.toml

      - name: Publish to crates.io
        run: |
          cargo build
          cargo build --target wasm32-unknown-unknown
          cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --allow-dirty
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
